"""Helpers for Norwegian municipalities, counties and region changes."""

from .norway import (
    add_current_municipality_info,
    add_municipality_info,
    get_county,
    get_county_for_municipality,
    get_county_name,
    get_current_municipality,
    get_current_municipality_ids,
    get_current_region_ids,
    get_municipality,
    get_municipality_name,
    get_region_history,
    get_region_transitions,
    load_current_municipalities,
    load_region_transitions,
    load_regions_history,
    normalize_county_id,
    normalize_municipality_id,
    trace_region_to_current,
)

__all__ = [
    "add_current_municipality_info",
    "add_municipality_info",
    "get_county",
    "get_county_for_municipality",
    "get_county_name",
    "get_current_municipality",
    "get_current_municipality_ids",
    "get_current_region_ids",
    "get_municipality",
    "get_municipality_name",
    "get_region_history",
    "get_region_transitions",
    "load_current_municipalities",
    "load_region_transitions",
    "load_regions_history",
    "normalize_county_id",
    "normalize_municipality_id",
    "trace_region_to_current",
]
